### PR TITLE
Fix #283: Fix Non functional nav links on landing page

### LINKED ISSUE #283: 🐛 Bug Report:  Landing Page Navigation Links are not functional
### 📜 Description

The nav links on the landing page are not functional 

### 👟 Reproduction steps

Go to https://altcampv1.netlify.app
Click on home or about or features link
It does not go anywhere

### 👍 Expected behavior

Clicking the nav links should scroll down to the various sections 

### 👎 Actual Behavior with Screenshots

image

### 📃 Provide any additional context for the Bug.

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/AltCamp/altcampv1-frontend/blob/dev/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by t-bello7**
This PR...

## Changes

- Changes the scroll effect to sections on the landing page

## Fixes
- #283 

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [x] added/updated a component
- [x] fixed a bug
- [ ] added/updated a new route
- [ ] added or changed css styles

### CODE REVIEW

File: src/pages/landing/landing.jsx [hunk 1]
```diff
@@ -160,7 +169,7 @@ const Landing = () => {
           </div>
         </div>
       </div>
-      <div className={landingPageStyles['benefits-area']}>
+      <div className={landingPageStyles['benefits-area']} ref={featuresRef}>
```
Comment (Boye95) [inline src/pages/landing/landing.jsx:171]: add ```overflow-y: scroll;``` to ```benefits-area``` styles. This will help push the element into view.

File: src/pages/landing/landing.jsx [hunk 2]
```diff
@@ -76,14 +85,14 @@ const Landing = () => {
             </p>
             <Link to="/account/login">
               <button>Get Started</button>
-            </Link>
+            </Link>Features
```
Comment (Boye95) [inline src/pages/landing/landing.jsx]: ``features`` should be removed as I believe it's a mistake

**Review by Boye95 — CHANGES_REQUESTED** [review]
Kindly work on the comments made and it would be great if you could apply the changes to the mobile hamburger menu list.

File: src/pages/landing/landing.jsx (hunk 2 above)
Comment (t-bello7) [reply src/pages/landing/landing.jsx]: Alright I would make the required changes

Comment (Boye95) [reply src/pages/landing/landing.jsx]: Thank you.

Comment (t-bello7) [reply src/pages/landing/landing.jsx]: I have made the following changes:
- remove features link 
- fix navigation links in hamburger menu

**Comment by Boye95** [comment]
altcampfeaterror1
@t-bello7 Check the image attached for the circled portion under the Get Started button in the Hero Section. I was referring to that when I mentioned that ``features`` be removed and not the ```Features``` Link. Please reach out if it's confusing. Thanks

**Review by Boye95 — APPROVED** [review]
@t-bello7  Thank you for contributing to AltCamp. We hope to see more of your issues and PRs

**Comment by Boye95** [comment]
@t-bello7 Thanks. Your changes have been approved and the PR & Issue closed.
